In [3]:
import pandas as pd
import numpy as np 
import seaborn as sns

In [10]:
df=pd.read_csv("marketing_campaign.csv", sep=';')

In [11]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0

In [13]:
df.shape

(2240, 29)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [15]:
df.describe()

,ID,Year_Birth,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
count,2240.000000,2240.000000,2216.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,...,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.000000,2240.0,2240.0,2240.000000
mean,5592.159821,1968.805804,52247.251354,0.444196,0.506250,49.109375,303.935714,26.302232,166.950000,37.525446,...,5.316518,0.072768,0.074554,0.072768,0.064286,0.013393,0.009375,3.0,11.0,0.149107
std,3246.662198,11.984069,25173.076661,0.538398,0.544538,28.962453,336.597393,39.773434,225.715373,54.628979,...,2.426645,0.259813,0.262728,0.259813,0.245316,0.114976,0.096391,0.0,0.0,0.356274
min,0.000000,1893.000000,1730.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
25%,2828.250000,1959.000000,35303.000000,0.000000,0.000000,24.000000,23.750000,1.000000,16.000000,3.000000,...,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
50%,5458.500000,1970.000000,51381.500000,0.000000,0.000000,49.000000,173.500000,8.000000,67.000000,12.000000,...,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
75%,8427.750000,1977.000000,68522.000000,1.000000,1.000000,74.000000,504.250000,33.000000,232.000000,50.000000,...,7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.0,11.0,0.000000
max,11191.000000,1996.000000,666666.000000,2.000000,2.000000,99.000000,1493.000000,199.000000,1725.000000,259.000000,...,20.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.0,11.0,1.000000

In [16]:
df.isnull().sum()

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [19]:
df.columns

Index(['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome',
       'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits',
       'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts',
       'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases',
       'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth',
       'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1',
       'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response'],
      dtype='object')

Starting WIth Data Cleaning

1) Dealing With Null Values

In [20]:
df['Income'] = df['Income'].fillna(
    df['Income'].median()
)

In [21]:
df.isnull().sum()

ID                     0
Year_Birth             0
Education              0
Marital_Status         0
Income                 0
Kidhome                0
Teenhome               0
Dt_Customer            0
Recency                0
MntWines               0
MntFruits              0
MntMeatProducts        0
MntFishProducts        0
MntSweetProducts       0
MntGoldProds           0
NumDealsPurchases      0
NumWebPurchases        0
NumCatalogPurchases    0
NumStorePurchases      0
NumWebVisitsMonth      0
AcceptedCmp3           0
AcceptedCmp4           0
AcceptedCmp5           0
AcceptedCmp1           0
AcceptedCmp2           0
Complain               0
Z_CostContact          0
Z_Revenue              0
Response               0
dtype: int64

2) Checking Duplicates

In [23]:
df.duplicated().sum()

np.int64(0)

3.Converting Date Column

In [24]:
df['Dt_Customer'] = pd.to_datetime(
    df['Dt_Customer']
)

In [25]:
df.dtypes

ID                              int64
Year_Birth                      int64
Education                      object
Marital_Status                 object
Income                        float64
Kidhome                         int64
Teenhome                        int64
Dt_Customer            datetime64[ns]
Recency                         int64
MntWines                        int64
MntFruits                       int64
MntMeatProducts                 int64
MntFishProducts                 int64
MntSweetProducts                int64
MntGoldProds                    int64
NumDealsPurchases               int64
NumWebPurchases                 int64
NumCatalogPurchases             int64
NumStorePurchases               int64
NumWebVisitsMonth               int64
AcceptedCmp3                    int64
AcceptedCmp4                    int64
AcceptedCmp5                    int64
AcceptedCmp1                    int64
AcceptedCmp2                    int64
Complain                        int64
Z_CostContact                   int64
Z_Revenue                       int64
Response                        int64
dtype: object

Feature Engineering

1.Creating Age

In [27]:
df['Age'] = 2026 - df['Year_Birth']

2.Creating Children Column

In [28]:
df['Children'] = (
    df['Kidhome']
    + df['Teenhome']
)

3.Creating Total Spending Column

In [29]:
df['Total_Spending'] = (
      df['MntWines']
    + df['MntFruits']
    + df['MntMeatProducts']
    + df['MntFishProducts']
    + df['MntSweetProducts']
    + df['MntGoldProds']
)

4.Creating Customer Tenure Column

In [30]:
df['Customer_Tenure'] = (
    2026 -
    df['Dt_Customer'].dt.year
)

5. Creating Age_Group

In [31]:
df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[18,30,45,60,100],
    labels=[
        'Young Adult',
        'Adult',
        'Middle Age',
        'Senior'
    ]
)

6.Creating Income Groups

In [33]:
df['Income_Group'] = pd.qcut(
    df['Income'],
    q=3,
    labels=[
        'Low Income',
        'Middle Income',
        'High Income'
    ]
)

7.Creating Total Purchases Column

In [34]:
df['Total_Purchases'] = (
      df['NumWebPurchases']
    + df['NumCatalogPurchases']
    + df['NumStorePurchases']
)

8.Creating Acceptance Count Column

In [35]:
df['Accepted_Campaigns'] = (
      df['AcceptedCmp1']
    + df['AcceptedCmp2']
    + df['AcceptedCmp3']
    + df['AcceptedCmp4']
    + df['AcceptedCmp5']
)

9.Creating High Value Customer Flag

In [36]:
df['Customer_Segment'] = np.where(
    df['Total_Spending'] >=
    df['Total_Spending'].median(),
    'High Value',
    'Low Value'
)

In [37]:
df.shape

(2240, 38)

In [38]:
df.head()

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,Response,Age,Children,Total_Spending,Customer_Tenure,Age_Group,Income_Group,Total_Purchases,Accepted_Campaigns,Customer_Segment
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,1,69,0,1617,14,Senior,Middle Income,22,0,High Value
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,0,72,2,27,12,Senior,Middle Income,4,0,Low Value
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,0,61,0,776,13,Senior,High Income,20,0,High Value
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,0,42,1,53,12,Adult,Low Income,6,0,Low Value
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,0,45,1,422,12,Adult,Middle Income,14,0,High Value

Starting WIth EDA

1.Revenue Overview

i)Total Revenue

In [43]:
print(
    "Total Revenue:",
    round(df['Total_Spending'].sum(),2)
)

Total Revenue: 1356988

ii)Average Spending

In [44]:
print(
    "Average Spending:",
    round(df['Total_Spending'].mean(),2)
)

Average Spending: 605.8

iii)Maximum Spending

In [45]:
print(
    "Maximum Spending:",
    round(df['Total_Spending'].max(),2)
)

Maximum Spending: 2525

iv)Minimum Spending

In [46]:
print(
    "Minimum Spending:",
    round(df['Total_Spending'].min(),2)
)

Minimum Spending: 5

2.Education Analysis

i)Spending by Education Level

In [47]:
education_spending = (
    df.groupby('Education')
    ['Total_Spending']
    .sum()
    .sort_values(
        ascending=False
    )
)

education_spending

Education
Graduation    698626
PhD           326791
Master        226359
2n Cycle      100795
Basic           4417
Name: Total_Spending, dtype: int64

3.Marital Status Analysis

In [48]:
marital_spending = (
    df.groupby('Marital_Status')
    ['Total_Spending']
    .sum()
    .sort_values(
        ascending=False
    )
)

marital_spending

Marital_Status
Married     510453
Together    352865
Single      291112
Divorced    141666
Widow        56889
Absurd        2385
YOLO           848
Alone          770
Name: Total_Spending, dtype: int64

4.Age Group Analysis

In [49]:
age_group_analysis = (
    df.groupby('Age_Group')
    ['Total_Spending']
    .sum()
    .sort_values(
        ascending=False
    )
)

age_group_analysis

C:\Users\garge\AppData\Local\Temp\ipykernel_20676\2981608377.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Age_Group')

Age_Group
Senior         601037
Middle Age     531345
Adult          222528
Young Adult       138
Name: Total_Spending, dtype: int64

5.Income Group Analysis

In [52]:
income_group_analysis = (
    df.groupby('Income_Group')
    ['Total_Spending']
    .sum()
    .sort_values(
        ascending=False
    )
)

income_group_analysis

C:\Users\garge\AppData\Local\Temp\ipykernel_20676\4191037864.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Income_Group')

Income_Group
High Income      944368
Middle Income    341180
Low Income        71440
Name: Total_Spending, dtype: int64

6.Product Category Spending

i)Wines

In [53]:
print(
    "Wine Spending:",
    df['MntWines'].sum()
)

Wine Spending: 680816

ii)Fruits

In [54]:
print(
    "Fruit Spending:",
    df['MntFruits'].sum()
)

Fruit Spending: 58917

iii)Meat Products

In [55]:
print(
    "Meat Spending:",
    df['MntMeatProducts'].sum()
)

Meat Spending: 373968

iv)Fish Products

In [56]:
print(
    "Fish Spending:",
    df['MntFishProducts'].sum()
)

Fish Spending: 84057

vi)Sweet Products

In [57]:
print(
    "Sweet Spending:",
    df['MntSweetProducts'].sum()
)

Sweet Spending: 60621

vii)Gold Products

In [58]:
print(
    "Gold Spending:",
    df['MntGoldProds'].sum()
)

Gold Spending: 98609

7.Purchase Channel Analysis

In [65]:

purchase_channel = {
    "Web Purchases":
    df['NumWebPurchases'].sum(),

    "Catalog Purchases":
    df['NumCatalogPurchases'].sum(),

    "Store Purchases":
    df['NumStorePurchases'].sum()
}

purchase_channel

{'Web Purchases': np.int64(9150),
 'Catalog Purchases': np.int64(5963),
 'Store Purchases': np.int64(12970)}

8.Campaign Acceptance Analysis

In [66]:
campaign_acceptance = (
    df[
        ['AcceptedCmp1',
         'AcceptedCmp2',
         'AcceptedCmp3',
         'AcceptedCmp4',
         'AcceptedCmp5']
    ]
    .sum()
    .sort_values(
        ascending=False
    )
)

campaign_acceptance

AcceptedCmp4    167
AcceptedCmp3    163
AcceptedCmp5    163
AcceptedCmp1    144
AcceptedCmp2     30
dtype: int64

9.Customer Segment Analysis

In [67]:
segment_analysis = (
    df.groupby(
        'Customer_Segment'
    )
    ['Total_Spending']
    .sum()
)

segment_analysis

Customer_Segment
High Value    1232643
Low Value      124345
Name: Total_Spending, dtype: int64

10.Response Analysis

In [68]:
df['Response'].value_counts()

Response
0    1906
1     334
Name: count, dtype: int64

11.Complaint Analysis

In [69]:
df['Complain'].value_counts()

Complain
0    2219
1      21
Name: count, dtype: int64

12.Top 10 Customers

In [70]:
top_customers = (
    df.groupby('ID')
    ['Total_Spending']
    .sum()
    .sort_values(
        ascending=False
    )
    .head(10)
)

top_customers

ID
5350     2525
5735     2525
1763     2524
4580     2486
4475     2440
5453     2352
10133    2349
9010     2346
5386     2302
6024     2302
Name: Total_Spending, dtype: int64

13.Web Visits Analysis

In [71]:
df['NumWebVisitsMonth'].describe()

count    2240.000000
mean        5.316518
std         2.426645
min         0.000000
25%         3.000000
50%         6.000000
75%         7.000000
max        20.000000
Name: NumWebVisitsMonth, dtype: float64

14.Recency Analysis

In [72]:
df['Recency'].describe()

count    2240.000000
mean       49.109375
std        28.962453
min         0.000000
25%        24.000000
50%        49.000000
75%        74.000000
max        99.000000
Name: Recency, dtype: float64

15.Campaign Response Rate

In [73]:
response_rate = (
    df['Response']
    .mean()
) * 100

print(
    "Campaign Response Rate:",
    round(response_rate,2),
    "%"
)

Campaign Response Rate: 14.91 %

Exporting Dimension Tables and Fact Table

Dim_Customers

In [74]:
dim_customers = df[[
    'ID',
    'Year_Birth',
    'Age',
    'Age_Group',
    'Education',
    'Marital_Status',
    'Income',
    'Income_Group',
    'Children',
    'Customer_Segment'
]].drop_duplicates()

dim_customers.to_csv(
    "dim_customers.csv",
    index=False,
    encoding='utf-8-sig'
)

Dim_Campaigns

In [75]:
dim_campaigns = df[[
    'ID',
    'AcceptedCmp1',
    'AcceptedCmp2',
    'AcceptedCmp3',
    'AcceptedCmp4',
    'AcceptedCmp5',
    'Response'
]]

dim_campaigns.to_csv(
    "dim_campaigns.csv",
    index=False,
    encoding='utf-8-sig'
)

Fact_Sales

In [77]:
fact_sales = df[[
    'ID',
    'Dt_Customer',
    'Recency',
    'MntWines',
    'MntFruits',
    'MntMeatProducts',
    'MntFishProducts',
    'MntSweetProducts',
    'MntGoldProds',
    'Total_Spending',
    'NumDealsPurchases',
    'NumWebPurchases',
    'NumCatalogPurchases',
    'NumStorePurchases',
    'NumWebVisitsMonth',
    'Total_Purchases'
]]

fact_sales.to_csv(
    "fact_sales.csv",
    index=False,
    encoding='utf-8-sig'
)